(function(app){
    var game = {
    "id":"0",
    "reg4Pile":{
    "cards":[
        {
            "rank":"EIGHT",
            "suit":"SPADE",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"SEVEN",
            "suit":"DIAMOND",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"THREE",
            "suit":"CLUB",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"ACE",
            "suit":"SPADE",
            "cardState":"FACE_UP",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":false,
            "faceUp":true
        }
    ],
        "size":4,
        "topCard":{
        "rank":"ACE",
            "suit":"SPADE",
            "cardState":"FACE_UP",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":false,
            "faceUp":true
    }
},
    "reg3Pile":{
    "cards":[
        {
            "rank":"JACK",
            "suit":"DIAMOND",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"NINE",
            "suit":"DIAMOND",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"SEVEN",
            "suit":"CLUB",
            "cardState":"FACE_UP",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":false,
            "faceUp":true
        }
    ],
        "size":3,
        "topCard":{
        "rank":"SEVEN",
            "suit":"CLUB",
            "cardState":"FACE_UP",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":false,
            "faceUp":true
    }
},
    "reg2Pile":{
    "cards":[
        {
            "rank":"TWO",
            "suit":"HEART",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"FOUR",
            "suit":"SPADE",
            "cardState":"FACE_UP",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":false,
            "faceUp":true
        }
    ],
        "size":2,
        "topCard":{
        "rank":"FOUR",
            "suit":"SPADE",
            "cardState":"FACE_UP",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":false,
            "faceUp":true
    }
},
    "reg1Pile":{
    "cards":[
        {
            "rank":"ACE",
            "suit":"DIAMOND",
            "cardState":"FACE_UP",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":false,
            "faceUp":true
        }
    ],
        "size":1,
        "topCard":{
        "rank":"ACE",
            "suit":"DIAMOND",
            "cardState":"FACE_UP",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":false,
            "faceUp":true
    }
},
    "reg5Pile":{
    "cards":[
        {
            "rank":"QUEEN",
            "suit":"SPADE",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"TEN",
            "suit":"SPADE",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"EIGHT",
            "suit":"HEART",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"NINE",
            "suit":"SPADE",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"SIX",
            "suit":"DIAMOND",
            "cardState":"FACE_UP",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":false,
            "faceUp":true
        }
    ],
        "size":5,
        "topCard":{
        "rank":"SIX",
            "suit":"DIAMOND",
            "cardState":"FACE_UP",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":false,
            "faceUp":true
    }
},
    "reg6Pile":{
    "cards":[
        {
            "rank":"KING",
            "suit":"SPADE",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"SEVEN",
            "suit":"SPADE",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"KING",
            "suit":"DIAMOND",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"FIVE",
            "suit":"DIAMOND",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"THREE",
            "suit":"DIAMOND",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"TEN",
            "suit":"HEART",
            "cardState":"FACE_UP",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":false,
            "faceUp":true
        }
    ],
        "size":6,
        "topCard":{
        "rank":"TEN",
            "suit":"HEART",
            "cardState":"FACE_UP",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":false,
            "faceUp":true
    }
},
    "reg7Pile":{
    "cards":[
        {
            "rank":"QUEEN",
            "suit":"HEART",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"SIX",
            "suit":"HEART",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"EIGHT",
            "suit":"DIAMOND",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"FIVE",
            "suit":"HEART",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"QUEEN",
            "suit":"CLUB",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"FOUR",
            "suit":"CLUB",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"NINE",
            "suit":"CLUB",
            "cardState":"FACE_UP",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":false,
            "faceUp":true
        }
    ],
        "size":7,
        "topCard":{
        "rank":"NINE",
            "suit":"CLUB",
            "cardState":"FACE_UP",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":false,
            "faceUp":true
    }
},
    "heartsPile":{
    "cards":[

    ],
        "size":0,
        "topCard":null
},
    "clubsPile":{
    "cards":[

    ],
        "size":0,
        "topCard":null
},
    "spadesPile":{
    "cards":[

    ],
        "size":0,
        "topCard":null
},
    "discardPile":{
    "cards":[

    ],
        "size":0,
        "topCard":null
},
    "diamondsPile":{
    "cards":[

    ],
        "size":0,
        "topCard":null
},
    "drawPile":{
    "cards":[
        {
            "rank":"KING",
            "suit":"HEART",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"JACK",
            "suit":"HEART",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"SIX",
            "suit":"SPADE",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"TWO",
            "suit":"CLUB",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"SEVEN",
            "suit":"HEART",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"QUEEN",
            "suit":"DIAMOND",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"FOUR",
            "suit":"HEART",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"NINE",
            "suit":"HEART",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"FIVE",
            "suit":"SPADE",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"TWO",
            "suit":"DIAMOND",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"ACE",
            "suit":"HEART",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"EIGHT",
            "suit":"CLUB",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"TWO",
            "suit":"SPADE",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"SIX",
            "suit":"CLUB",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"FOUR",
            "suit":"DIAMOND",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"ACE",
            "suit":"CLUB",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"JACK",
            "suit":"CLUB",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"FIVE",
            "suit":"CLUB",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"KING",
            "suit":"CLUB",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"THREE",
            "suit":"HEART",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"THREE",
            "suit":"SPADE",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"TEN",
            "suit":"DIAMOND",
            "cardState":"FACE_DOWN",
            "color":"RED",
            "black":false,
            "red":true,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"JACK",
            "suit":"SPADE",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        },
        {
            "rank":"TEN",
            "suit":"CLUB",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
        }
    ],
        "size":24,
        "topCard":{
        "rank":"TEN",
            "suit":"CLUB",
            "cardState":"FACE_DOWN",
            "color":"BLACK",
            "black":true,
            "red":false,
            "faceDown":true,
            "faceUp":false
    }
}
};

    var GameService = function(){
        var self = {};

        self.getGame = function(){
            return game;
        };

        return self;
    };

    app.GameService = GameService;
    app.factory('gameService', GameService);

})(solitaire)